"""Transport and discovery interfaces."""

from __future__ import annotations

from typing import Protocol


class TransportPort(Protocol):
    def connect(self, host: str, port: int, timeout: float = 5.0) -> None: ...

    def disconnect(self) -> None: ...

    def send(self, message: str) -> None: ...

    def recv(self, timeout: float = 0.0) -> str | None: ...

    def is_connected(self) -> bool: ...


class DiscoveryPort(Protocol):
    def discover(self, discovery_port: int, timeout: float = 1.5) -> tuple[str, int] | None: ...

    def advertise(self, discovery_port: int, websocket_port: int) -> None: ...

    def stop_advertising(self) -> None: ...
